name: pyrethrum
version: 0.1.0.0
github: "githubuser/simple-hpack"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2018 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/simple-hpack#readme>

dependencies:
  - pyrethrum-extras
  - containers
  - extra
  - text
  - transformers-either
  - aeson
  - yaml
  - pretty-show
  - dlist
  - mtl
  - raw-strings-qq
  - polysemy
  - unliftio
  - polysemy-plugin
  - relude
  - name: base
    mixin:
      - hiding (Prelude)
  - name: relude
    mixin:
      - (Relude as Prelude, Data.Text) 

ghc-options:
  # - -threaded
  - -fmax-pmcheck-models=10000000
  - -ferror-spans
  - -fprint-potential-instances
  # - -dth-dec-file -- generate template haskell
  - -j3 #number of cores used by ghc in compiling

  # threading related options only has an effect for exes
  # - -threaded
  # - -rtsopts
  # - -with-rtsopts=-N

  # - -O2
  # TODO: prgma to turn optimisations on for non-dev build
  # - -O2
  # - -flate-specialise # reqiuired for polysemy
  # - -fspecialise-aggressively # reqiuired for polysemy
  # - -Werror
  - -O0
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fplugin=Polysemy.Plugin
  - -fwarn-tabs
  - -fno-warn-unused-imports
  - -fno-warn-missing-signatures
  - -fno-warn-type-defaults
  - -fno-warn-unused-matches
  - -fno-warn-unused-binds
  - -fno-warn-unused-do-bind
  - -fwrite-ide-info
  # - -fdefer-type-errors
  - -Wno-overlapping-patterns

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - ConstrainedClassMethods
  - ConstraintKinds
  - DisambiguateRecordFields
  - DuplicateRecordFields
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - ExtendedDefaultRules
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - LiberalTypeSynonyms
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoFieldSelectors
  - NumericUnderscores
  - OverloadedStrings
  - OverloadedRecordDot
  - PartialTypeSignatures
  - PatternSynonyms
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

# _testDep: &testdependencies
#   - tasty
#   - tasty-hunit
#   - tasty-hedgehog
#   - tasty-discover
#   - hedgehog
#   # - pyrethrum
#   - bytestring

library:
  when:
    # https://github.com/sol/hpack#handling-of-paths_-modules
    - condition: false
      other-modules: Paths_pyrethrum
  source-dirs:
    - src
    # this enables eval in ghcid - remove test when finally compiling
    - test
  dependencies:
    # test dependencies remove in split config
    - tasty
    - tasty-hunit
    - tasty-hedgehog
    - tasty-discover
    - hedgehog
    - bytestring
    # end test dependencies remove in split config
    - deepseq
    - unordered-containers
    - template-haskell
    - bytestring
    - fmt

#  reinstate when LHS can live load multiple modules
# use God library for now - https://www.haskellforall.com/2021/05/module-organization-guidelines-for.html

tests:
  pyrethrum-test:
    main: Main.hs
    source-dirs:
      - test
    dependencies:
      - pyrethrum
      # test dependencies remove in split config
      - tasty
      - tasty-hunit
      - tasty-hedgehog
      - tasty-discover
      - hedgehog
      - bytestring

build-tools: tasty-discover:tasty-discover
