name: pyrethrum
version: 0.1.0.0
github: "githubuser/simple-hpack"
license: MIT
author: "Author name here"
maintainer: "example@example.com"
copyright: "2018 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/simple-hpack#readme>

# command line:
# development
# cabal build --flags="-optimised +godLibrary"
# test
# cabal ci --flags="+optimised -godLibrary"

flags:
  # use God library for debugging now - https://www.haskellforall.com/2021/05/module-organization-guidelines-for.html
  # can probably be depricated when HLS can live load multiple modules
  godLibrary:
    description: compile all modules (including tests) into one module
    manual: true
    default: true
  optimised:
    description: is the exe optimised
    manual: true
    default: false

verbatim:
  - cabal-version: 3.6
  - |
    common optimisation
      if flag(optimised)
        ghc-options: -O2
      else
        ghc-options: -O0
  - |
    common testLibProps
      build-depends:
        tasty
        , tasty-hunit
        , tasty-hedgehog
        , tasty-discover
        , hedgehog
        , bytestring
        , falsify
      hs-source-dirs:
        test
  - |
    common pyrethrumProps
      hs-source-dirs:
        src
      build-depends:
        deepseq
        , unordered-containers
        , template-haskell
        , fmt
  - |
    common libImports
      if flag(godLibrary)
        import:
          testLibProps, optimisation
      else
        import:
          optimisation
  - |
    common reludeImports
      build-depends:
       base
       , relude
       , pyrethrum-extras
      mixins:
        base hiding (Prelude),
        relude (Relude as Prelude, Data.Text, Relude.Unsafe as Unsafe)

dependencies:
  - aeson
  - base-prelude # needed for IOError
  - bytestring
  - chronos
  - containers
  - directory
  - dlist
  - exceptions
  - effectful-core
  - effectful
  - effectful-plugin
  - effectful-th
  - extra
  - hashable
  - mtl
  - path # - version set in extra deps - until can roll forward
  - path-io # -
  - pretty-show
  - pyrethrum-extras
  # since removing pyrelude
  - text
  - time # need for timezone which is missing from chronos
  - transformers-either
  - random
  - raw-strings-qq
  # - relude
  - unliftio
  - yaml
  # used to talk to ghecko driver
  - http-client
  - http-types
  - req
  # webdriver used in TestdemoSelenium
  - webdriver-w3c
  # - name: base
  #   mixin:
  #     - hiding (Prelude)
  # - name: relude
  #   mixin:
  #     - (Relude as Prelude, Data.Text, Relude.Unsafe as Unsafe)

ghc-options:
  # - -threaded
  - -fmax-pmcheck-models=10000000
  - -ferror-spans
  - -fprint-potential-instances
  # - -dth-dec-file -- generate template haskell
  # - -j3 #number of cores used by ghc in compiling

  # threading related options only has an effect for exes
  # - -threaded
  # - -rtsopts
  # - -with-rtsopts=-N

  # - -O2
  # - -Werror
  # - *optimisation
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fplugin=Effectful.Plugin
  - -fwarn-tabs
  - -fwrite-ide-info
  # - -fno-warn-unused-imports
  # - -fno-warn-missing-signatures
  - -fno-warn-type-defaults
  # - -fno-warn-unused-matches
  # - -fno-warn-unused-binds
  - -fno-warn-unused-do-bind
  - -Wno-overlapping-patterns
  # todo: more researchon this: https://well-typed.com/blog/2023/02/interface-files-with-core/
  - -fprefer-byte-code 
  - -fbyte-code-and-object-code
  # https://gitlab.haskell.org/ghc/ghc/-/issues/24278
  - -fno-break-points
  # this would be nice but seems to break ghcid
  # - -Werror=prepositive-qualified-module
  # - -fdefer-type-error
  # profiling
  # - -ddump-to-file 
  # - -ddump-timings

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - ConstrainedClassMethods
  - ConstraintKinds
  - DisambiguateRecordFields
  - DuplicateRecordFields
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - ExtendedDefaultRules
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - LiberalTypeSynonyms
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoFieldSelectors
  - NumericUnderscores
  - OverloadedStrings
  - OverloadedRecordDot
  - PartialTypeSignatures
  - PatternSynonyms
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

# internal-libraries:
#   examples:
#     ghc-options: -O0
#     source-dirs:
#       - examples
#       # remove later
#       - src
#     dependencies:
#       - unordered-containers
#       - pyrethrum
#       - template-haskell
#     verbatim:
#       import: reludeImports

#   discover:
#     # change optimisation and move later
#     default-extensions:
#       - FieldSelectors
#     ghc-options: -O0
#     visibility: public
#     source-dirs:
#       - discover
#       # remove later
#     dependencies:
#       - algebraic-graphs     ^>= 0.7
#       - base                 ^>= 4.17.0.0 || ^>= 4.18.0.0
#       - bytestring           ^>= 0.10.9.0 || ^>= 0.11.0.0
#       - containers           ^>= 0.6.2.1
#       - directory            ^>= 1.3.3.2
#       - filepath             ^>= 1.4.2.1
#       - generic-lens         ^>= 2.2.0.0
#       - ghc                  ^>= 9.4 || ^>= 9.6
#       - lens               
#       - mtl                  ^>= 2.2.2 || ^>= 2.3
#       - optparse-applicative
#       - regex-tdfa           ^>= 1.2.0.0 || ^>= 1.3.1.0
#       - text                 ^>= 2.0.1
#       - toml-reader          ^>= 0.2.0.0
#       - transformers         ^>= 0.5.6.2 || ^>= 0.6

library:
  when:
    # https://github.com/sol/hpack#handling-of-paths_-modules
    - condition: false
      other-modules: Paths_pyrethrum
  source-dirs:
    - src
    # remove later when finish most dev and move away from god modules
    # TODO: God modules probably not required with latest cabal spilt fix once and for all
    - test
    - examples
  dependencies:
    - deepseq
    - unordered-containers
    - template-haskell
    - fmt
  # verbatum needs to go last otherwise exposed module inference does not work
  verbatim:
    import: libImports, pyrethrumProps, reludeImports

# tests:
#   pyrethrum-test:
#     main: Main.hs
#     source-dirs:
#       - test
#     dependencies:
#       - pyrethrum
#     # verbatum needs to go last otherwise other module inference does not work
#     verbatim:
#       import: testLibProps, reludeImports
#     build-tools: tasty-discover:tasty-discover
