name:                pyrethrum
version:             0.1.0.0
github:              "githubuser/simple-hpack"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/simple-hpack#readme>

dependencies:
  - base
  - containers
  - extra
  - chronos
  - time
  - text
  - transformers-either
  - aeson
  - yaml
  - pretty-show
  - dlist
  - raw-strings-qq
  - polysemy
  - polysemy-plugin

ghc-options:
  - -fmax-pmcheck-models=10000000
  - -ferror-spans
  - -O0
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fplugin=Polysemy.Plugin
  - -fwarn-tabs
  - -fno-warn-unused-imports
  - -fno-warn-missing-signatures
  - -fno-warn-type-defaults
  - -fno-warn-unused-matches
  - -fno-warn-unused-binds
  - -fno-warn-unused-do-bind
  - -fwrite-ide-info

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - ConstrainedClassMethods
  - ConstraintKinds
  - DisambiguateRecordFields
  - DuplicateRecordFields
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - ExtendedDefaultRules
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - LiberalTypeSynonyms
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternSynonyms
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

library:
  source-dirs: src
  dependencies:
    - deepseq
    - unordered-containers
    - template-haskell
    - bytestring
    - mtl
    - fmt