name:                pyrethrum
version:             0.1.0.0
github:              "githubuser/simple-hpack"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/simple-hpack#readme>

dependencies:
  - base

ghc-options:
  - -fmax-pmcheck-models=10000000
  - -ferror-spans
  # - -dth-dec-file -- generate template haskell

  - -O0
  # - -O2
  # - -flate-specialise # reqiuired for polysemy
  # - -fspecialise-aggressively # reqiuired for polysemy
  # - -Werror
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fwarn-tabs
  - -fno-warn-unused-imports
  - -fno-warn-missing-signatures
  - -fno-warn-type-defaults
  - -fno-warn-unused-matches
  - -fno-warn-unused-binds
  - -fno-warn-unused-do-bind
  - -fwrite-ide-info
  # - -fdefer-type-errors

library:
  source-dirs: src

tests:
  pyrethrum-test:
    main:                DemoTest.hs
    source-dirs:        
    - test
    dependencies:
    - pyrethrum