name: pyrethrum
version: 0.1.0.0
github: "githubuser/simple-hpack"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2018 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/simple-hpack#readme>

dependencies:
  - base
  - pyrelude
  - containers
  - extra
  - text
  - transformers-either
  - aeson
  - yaml
  - pretty-show
  - dlist
  - mtl
  - raw-strings-qq
  - polysemy
  - unliftio
  - polysemy-plugin
  
ghc-options:
  # - -threaded
  - -fmax-pmcheck-models=10000000
  - -ferror-spans
  - -fprint-potential-instances
  # - -dth-dec-file -- generate template haskell
  - -j3 #number of cores used by ghc in compiling

  # threading related options only has an effect for exes
  # - -threaded 
  # - -rtsopts 
  # - -with-rtsopts=-N

  # - -O2
  # TODO: prgma to turn optimisations on for non-dev build
  # - -O2
  # - -flate-specialise # reqiuired for polysemy
  # - -fspecialise-aggressively # reqiuired for polysemy
  # - -Werror
  - -O0
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fplugin=Polysemy.Plugin
  - -fwarn-tabs
  - -fno-warn-unused-imports
  - -fno-warn-missing-signatures
  - -fno-warn-type-defaults
  - -fno-warn-unused-matches
  - -fno-warn-unused-binds
  - -fno-warn-unused-do-bind
  - -fwrite-ide-info
  # - -fdefer-type-errors

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - ConstrainedClassMethods
  - ConstraintKinds
  - DisambiguateRecordFields
  - DuplicateRecordFields
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - ExtendedDefaultRules
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - LiberalTypeSynonyms
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternSynonyms
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

# _testDep: &testdependencies
#   - tasty
#   - tasty-hunit
#   - tasty-hedgehog
#   - tasty-discover
#   - hedgehog
#   # - pyrethrum
#   - bytestring

library:
  when:
    # https://github.com/sol/hpack#handling-of-paths_-modules
    - condition: false
      other-modules: Paths_pyrethrum
  source-dirs:
    - src
    # this enables eval in ghcid - remove test when finally compiling
    - test
  dependencies:
    # test dependencies remove in split config 
    - tasty
    - tasty-hunit
    - tasty-hedgehog
    - tasty-discover
    - hedgehog
    - bytestring
    # end test dependencies remove in split config 
    - deepseq
    - unordered-containers
    - template-haskell
    - bytestring
    - fmt
  extra-deps:
    # mine
    - primitive-unlifted-0.1.3.1
    - git: https://github.com/theGhostJW/pyrelude
      commit: "4c7196461914f8cab994356f9359e00e76a1c842"
    - chronos-1.1.3@sha256:6e817a0e265c9f7a4451404597e010ad7b4aebfe38762c6ab2cb514fb5b455d2,3933
    - encode-string-0.1.0.0@sha256:b960508cede9547f5af3ade3d07ed79cbdb575ed128fcac1d7cff0a1162260ce,1864
    - bytebuild-0.3.9.0@sha256:8639f2640dc5905d6d57d74d391cdff47b16218aa80420fa6ef35e344fe1b134,3196
    - byteslice-0.2.6.0@sha256:ec2dab1d8730cea844d3b3fc6b890e038c32cac2595426904d93fad7c836f5c5,2482
    - bytesmith-0.3.8.0@sha256:c17c0eb6702dfa209b2e5e7496d72f770d0b5dc2adf30da62f611966ebbb69f5,1863
    - contiguous-0.6.1@sha256:8ee83eaf335466fb11e85531987af93c0f567b4d0b2e1e74f3dd3e86fe9ab852,1968
    - run-st-0.1.1.0@sha256:a43245bb23984089016772481bf52bfe63eaff0c5040303f69c9b15e80872fdc,883

#  reinstate when LHS can live load multiple modules
# use God library for now - https://www.haskellforall.com/2021/05/module-organization-guidelines-for.html

# tests:
#   pyrethrum-test:
#     main:                driver.hs
#     source-dirs:
#     - test
#     dependencies: *testdependencies

